name: Build
on:
  workflow_dispatch:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Install dependencies
        run: ./dependencies.sh
        
      - name: Move ffmpeg-windows-build-helpers
        run: mv -v ./ffmpeg-windows-build-helpers/* ./
        
      - name: Compile FFmpeg using ffmpeg-windows-build-helpers
        run: ./cross_compile_ffmpeg.sh --ffmpeg-source-dir=$GITHUB_WORKSPACE/ffmpeg-source --gcc-cpu-count=2 --disable-nonfree=n --sandbox-ok=y --compiler-flavors=win32
        
      - name: 7-Zip FFmpeg win32 nonfree
        working-directory: ffmpeg-source
        run: 7z a ffmpeg-win32-nonfree.7z ffmpeg.exe ffprobe.exe ffplay.exe -mx=9
        
      - name: Upload FFmpeg win32 nonfree
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-win32-nonfree
          path: ffmpeg-source/ffmpeg-win32-nonfree.7z
          
      - name: Get current FFmpeg git commit date
        id: git-date
        working-directory: ffmpeg-source
        run: |
          echo "::set-output name=git-date::$(git log -1 --format=%ci)"
          
    outputs:
      git-date: ${{ steps.git-date.outputs.git-date }}
          
  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download all builds
        uses: actions/download-artifact@v2
        
      - name: Get current date & time
        id: date-time
        run: |
          echo "::set-output name=date-time::$(date +'%Y-%m-%d %H:%M')"
          echo "::set-output name=date-time-tag::$(date +'%Y-%m-%d-%H-%M')"
        
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "#${{ github.run_number }}"
          release_name: "#${{ github.run_number }}"
          draft: false
          prerelease: false
          
      - name: Upload FFmpeg win32 nonfree Release Asset
        uses: actions/upload-release-asset@v1
        with:
          name: ${{ steps.date-time.outputs.date-time }}
          tag_name: ${{ steps.date-time.outputs.date-time-tag }}
          body: FFmpeg nonfree git-${{ needs.build.outputs.git-date }} built on ${{ steps.date-time.outputs.date-time }}
          files: ffmpeg-win32-nonfree/ffmpeg-win32-nonfree.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
