  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download all builds
        uses: actions/download-artifact@v2
        
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "#${{ github.run_number }}"
          release_name: "#${{ github.run_number }}"
          draft: false
          prerelease: false
          
      - name: Upload FFmpeg win32 custom nonfree Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ffmpeg-win32-custom-nonfree/ffmpeg-win32-custom-nonfree.7z
          asset_name: ffmpeg-win32-custom-nonfree.7z
          asset_content_type: application/x-7z-compressed
